#!/bin/bash

function to_slack() {
  set -eu

  # メッセージを一時保存する場所
  MESSAGEFILE=$(mktemp -t webhooksXXXX)
  # 終了時に削除
  trap "rm ${MESSAGEFILE}" 0

echo '------------' >&2

  msg=''
  for x in "$@"
  do
    echo $x >&2
    msg="$msg\n$x"
  done
echo '------------' >&2

  #msg=$(echo $msg | sed -e 's/$/ \\n/g')
  echo ${msg} > ${MESSAGEFILE}

  # WebHookのURL
  URL=${WEBHOOK_URL}
  # 送信先のチャンネル
  CHANNEL=${CHANNEL:-${channel}}
  # botの名前
  BOTNAME=${BOTNAME:-${bot}}
  # 絵文字
  EMOJI=${EMOJI:-${emoji}}
  # 見出し
  HEAD=${HEAD:-"[${head}]\n"}

  # メッセージをシンタックスハイライト付きに整形
  msg=`cat ${MESSAGEFILE}`
  msg="${msg//\"/\\\"}"
  MESSAGE='```'$msg'```'

  # jsonを一時保存
  JSON=$(mktemp -t payload_jsonXXXX)

  # jsonを終了時に削除
  trap "rm ${JSON}" 0

echo '============'
echo $MESSAGE
echo '============'

  if [ -n "$EMOJI" ]; then
    echo 'payload={"channel": "'"${CHANNEL}"'", "username": "'"${BOTNAME}"'", "icon_emoji": "'"${EMOJI}"'", "text": "'"${HEAD}${MESSAGE}"'"}' > ${JSON}
  else
    echo 'payload={"channel": "'"${CHANNEL}"'", "username": "'"${BOTNAME}"'", "text": "'"${HEAD}${MESSAGE}"'"}' > ${JSON}
  fi

  # 送信
  curl -X POST -d @${JSON} ${URL} #> /dev/null
}
